let inputdiemly;
let inputdiemsinh;
let inputdiemhoa;
inputdiemly = prompt('nhap diem ly');
inputdiemsinh = prompt('nhap diem sinh');
inputdiemhoa = prompt('nhap diem hoa');
let diemly = parseInt(inputdiemly);
let diemsinh = parseInt(inputdiemsinh);
let diemhoa = parseInt(inputdiemhoa);
let tongdiem = diemly + diemsinh + diemhoa;
document.write('tong diem la '+tongdiem);
document.write('<br/>');
let diemtb = (diemly + diemsinh + diemhoa)/3;
document.write ('diem trung binh la '+diemtb);
